### PR TITLE
Minimal changes to make SFML compile on Julia 0.6

### PR DESCRIPTION
**Pull request by dbeach24**
This branch incorporates incremental changes I made to get `SFML.jl` to build and precompile on OS X using Julia 0.6.

### CODE REVIEW

**Comment by scls19fr** [comment]
Does it closes #37 ?

**Comment by dbeach24** [comment]
I think it should...  Will it be matter?

**Comment by s-celles** [comment]
I'd like to try https://github.com/kayhman/alicia (from https://boutique.ed-diamond.com/anciens-numeros/1246-gnulinux-magazine-205.html ) but it requires SFML.jl

**Comment by scls19fr** [comment]
Maybe you should rebase and run CI with Julia 0.6 (and nightly)

**Comment by dbeach24** [comment]
Thanks.  "Will it be matter" was supposed to say "will it be merged"? Ah, autocorrect...

**Comment by scls19fr** [comment]
Sorry I'm not an english speaker. I understood that as "Does it really matter?"... and yes it matters ;-)

**Pull request merged**
